### ISSUE TITLE
'GL/gl.h' file not found

### ISSUE THREAD

**Issue by carlostrub** [rust-qt/examples#11]
I constantly get the following build errors:

`'GL/gl.h' file not found`

However, that library is installed under 

`/usr/local/include/qt5/QtOpenGL/qgl.h`

Any ideas?

**Comment by Riateche** [comment]
You need to install OpenGL development headers. How to do that depends on your OS, e.g. on Debian-based systems you need to install `mesa-common-dev`.

**Comment by carlostrub** [comment]
The headers are present, but maybe under an unusual location, i.e.

`/usr/local/include/GL/gl.h`

which is the standard FreeBSD location. Any ideas why the compiler does not search there?

**Comment by Riateche** [comment]
What is your default C++ compiler? [This issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=195105) says about a similar problem with clang. You can try to specify `CPATH=/usr/local/include` environment variable to add the directory to the search list (this variable should be recognized by both clang and gcc).

**Comment by Riateche** [comment]
Closed because of inactivity.
