### ISSUE TITLE
slot callback is invalid

### ISSUE THREAD

**Issue by DreamSaddle** [rust-qt/examples#12]
![image](https://user-images.githubusercontent.com/31559386/88800390-aafcee80-d1da-11ea-91c4-335252930b2c.png)

the line 66, method1 register slot callback is right, console printed `fsdafsd` 
but line 70, method2 register is not right, invalid, I click button not invoke `on_trans_btn_clicked` method

why?

**Comment by Riateche** [comment]
What is the implementation of `StaticUpcast<QObject>` for this type? Slots created by `#[slot]` attribute will use the object returned from that implementation as the parent object, so if that object is deleted, the connection to your slot will be deregistered. You should make sure that the object returned by `StaticUpcast<QObject>` lives long enough.

Another possibility is that your `self` object got deleted. Slots created by `#[slot]` attribute retain a weak reference to `self`, so they won't prevent it from being deleted. Make sure you have strong references to `self`. You can write a `Drop` implementation for your type to check if it was deleted.

Please don't post code as images. Code in images cannot be copied and is hard to read.

**Comment by DreamSaddle** [comment]
@Riateche 
Thank you!   
I solved！extended the QObject live time. 
But must declared a variable in `QApplication::init` method. Otherwise it won't work.

Such as
```
#[derive(Debug)]
struct MainWindow {
    transText: Rc<TransText>,
    optLine: Rc<OptLine>,
}

pub fn startQt() {
    QApplication::init(|_| unsafe {
        let mainWindow = QMainWindow::new_0a();
        let windowWidget = QWidget::new_1a(&mainWindow);

        // I declared a variable in here, but not used
        let _mw = initWindowWidgets(&windowWidget);

        mainWindow.set_fixed_size_2a(700, 200);
        windowWidget.resize_1a(&mainWindow.size());
        mainWindow.set_window_title(&qs("Youdao Dict"));
        mainWindow.show();
        QApplication::exec()
    })
}


unsafe fn initWindowWidgets(windowWidget: &QBox<QWidget>) -> Rc<MainWindow> {
    let vBox = QVBoxLayout::new_1a(windowWidget);
    vBox.set_contents_margins_4a(0, 0, 0, 0);
    vBox.set_spacing(2);
    vBox.set_direction(Direction::Down);
    

    //初始化输入框
    let transText = TransText::new(&vBox);
    
    //初始化操作栏
    let _optLine = OptLine::new(&vBox, &transText);

    let mw = Rc::new(MainWindow{
        transText: transText,
        optLine: _optLine
    });
    mw
}
```
