### ISSUE TITLE
Method 'start' missing in QTimer

### ISSUE THREAD

**Issue by brmmm3** [rust-qt/examples#4]
When I try to compile the following code:
...
        let mut timer = QTimer::new_0a();
        timer.timeout().connect(&form.timer_timeout);
        timer.set_interval(300);
        timer.start();
...
 I get with "cargo build":

error[E0599]: no method named `start` found for type `cpp_core::cpp_box::CppBox<qt_core::QTimer>` in the current scope
  --> src\main.rs:73:15
   |
73 |         timer.start();
   |               ^^^^^ method not found in `cpp_core::cpp_box::CppBox<qt_core::QTimer>`

OS: Windows 10

**Comment by Riateche** [comment]
This is an overloaded method, so different versions of it have different names. You need `start_0a` (`0a` stands for "zero arguments"). See [documentation](https://docs.rs/qt_core/0.4.1/qt_core/struct.QTimer.html#method.start_0a).

**Comment by brmmm3** [comment]
Ah thanks. This fixes my issue.
